### ISSUE TITLE
直接弃用上个版本了?

### ISSUE THREAD

**Issue by whzooo** [yixiangling/abp-ng-alain#1]
这个版本 会迭代? 还是 会像上个版本一样弃用?

**Comment by yixiangling** [comment]
上一版本是迁移代码，把ng-alain的很多组件复制后进行修改，剔除了delon的依赖。那个版本迁移和维护复杂，不好跟随ng-alain以及ng-zorro版本更新。
这个版本没有对ng-alain做修改，只增加abp特有部分，其余内容都是ng-alain，对于国际化、token、acl等你都可以直接用ng-alain的方案，我已经把这些数据在初始化程序的时候填进去了。之后ng-alain升级也不会影响此项目。

**Comment by rqx110** [comment]
好多angular工程文件是不是没有提交上来啊？ clone下来没法用啊！

**Comment by whzooo** [comment]
> 好多angular工程文件是不是没有提交上来啊？ clone下来没法用啊！

吧 npm nodejs ng 升级到最新  然后 按照文档说明 进行按照配置. 这个工程里面的代码类似一个升级包 支持abp. 认真看文档.
