### ISSUE TITLE
nswag 更新service 后 报错.

### ISSUE THREAD

**Issue by whzooo** [yixiangling/abp-ng-alain#2]
import 'rxjs/add/operator/finally';(这句报错,如果删除了 项目正常运行. 但是每次更新都有这句.能直接去掉.或者保留解决错误吗?)

但是能找到对应的文件 对应的文件里面有一句
import 'rxjs-compat/add/operator/finally';

ERROR in ./src/app/core/abp/service-proxies/service-proxies.ts
Module not found: Error: Can't resolve 'rxjs/add/operator/finally' in 'D:\

**Comment by yixiangling** [comment]
这是nswag的生成模板对angular6&rxjs6支持的问题。

ABP官方提供的免费模板暂时还是angular5的，而ng-alain是angular6。你可以直接删掉这句
`import 'rxjs/add/operator/finally'`
rxjs6的finally本身也不是这么引入的，这句是旧版本的引入方法，直接删除没有影响

**Comment by yixiangling** [comment]
由于service.extensions.ts内引入了多余的import 'rxjs/add/operator/finally'导致，已将此内容删除
