### ISSUE TITLE
nswag默认使用 momentjs ,但是alain的date组件不支持.

### ISSUE THREAD

**Issue by whzooo** [yixiangling/abp-ng-alain#3]
nswag默认使用 momentjs ,但是alain的date组件不支持.
改成Date 后,  datepipe  不能正常工作.

**Comment by whzooo** [comment]
我找到问题了 但是解决不了. 
是多语言的问题  在 格式化的时候 调用 datefromat 函数  location 是空 造成了取不到本地化的文字.
这个怎么解决?

**Comment by whzooo** [comment]
<td>{{item.creationTime|date:"yyyy-MM-dd HH:mm:ss":undefined:"zh-Hans"}}  指定location 能正常.
那里破坏了 ng的 本地化?

**Comment by yixiangling** [comment]
可以在`share`模块或`core/i18n`中添加一个pipe来处理moment类型的格式化显示问题。
moment国际化配置可以参见：[http://momentjs.cn/docs/#/i18n/](http://momentjs.cn/docs/#/i18n/)

BTW：
如果你要对国际化有一个较合适的支持，那么你在使用格式化时尽可能传入语义化的格式化参数，比如`medium`而不是`yyyy-MM-dd HH:mm:ss`，你可以参见[https://www.angular.cn/api/common/DatePipe](https://www.angular.cn/api/common/DatePipe) 对格式化的方式来写这个pipe

**Comment by whzooo** [comment]
非常感谢回复

我仔细看了你的回复    并不能解决 问题.  moment的格式化是没问题的 问题在于 组件不支持. 
有问题的是datepipe 格式化的时候  需要调用国际化.         造成报错.
我反复测试了.  只要不在 继承apbmodule的页面都可以 正常       我跟踪代码  是因为 默认本地化 字符 被替代造成的.  但是我解决不了.
不知道我说的清楚吗?

**Comment by yixiangling** [comment]
abp.module.ts中ABP_PROVIDERS数组中的LOCALE_ID这项删掉就可以了。
datepipe在格式化时会获取locale，我这个注入是多余的，ng-alain已经有此项注入了

**Comment by semprone** [comment]
函数调用缺少参数
![image](https://user-images.githubusercontent.com/28696015/49527384-c1ab4f00-f8ec-11e8-8fdc-6531a57bb01b.png)
